name: CI Workflow

on:
  push:
    branches:
      - main

    paths:
      - '**.py'
      - '**.yml'

  pull_request:
    branches:
      - main

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.local/lib/python3.12/site-packages
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tox
        run: tox -e py

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=atomtr
            -Dsonar.projectKey=nomadix-api
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.sources=nseapi/

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
