name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-md pytest-emoji pytest-cov
      - name: Run tests
        uses: pavelzw/pytest-action@v2
        with:
          emoji: true
          job-summary: true
          custom-arguments: --cov --cov-report=xml
          report-title: Test Report
          
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
